#cloud-config

yum_repos:
  baseos:
    gpgcheck: false
    baseurl: "http://172.22.1.220:80//install/rhels9.2.0/x86_64/BaseOS"
  appstream:
    gpgcheck: false
    baseurl: "http://172.22.1.220:80//install/rhels9.2.0/x86_64/AppStream"

package_update: true

packages:
  - qemu-guest-agent

runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service

ssh_authorized_keys:
  - ${public_key_openssh}

write_files:
  - content: |
      ${install_mkdocs_site}
    path: /root/install_mkdocs_site.sh
    permissions: '0777'

power_state:
  delay: 30
  mode: reboot
  message: Rebooting machine
