#cloud-config

yum_repos:
  baseos:
    gpgcheck: false
    baseurl: ${baseos_repo_url}
  appstream:
    gpgcheck: false
    baseurl: ${appstream_repo_url}

package_update: true

packages:
  - qemu-guest-agent

runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service

ssh_authorized_keys:
  - ${public_key_openssh}

write_files:
  - content: |
      ${indent(6,build_mkdocs_site)}
    path: /root/build_mkdocs_site.sh
    permissions: '0777'

power_state:
  delay: now
  mode: reboot
  message: Rebooting machine
