#cloud-config

package_update: true

packages:
  - qemu-guest-agent
  - vim
  - git
  - python3-pip

runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service

ssh_authorized_keys:
  - ${public_key_openssh}

power_state:
  delay: 30
  mode: reboot
  message: Rebooting machine